apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test-deployment
  labels:
    app: k8s-test-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: k8s-test-deployment
      labels:
        app: k8s-test-deployment
    spec:

      containers:
        - name: k8s-test-springboot
          image: avgdima/k8s-test-springboot:2
          imagePullPolicy: IfNotPresent
          livenessProbe:
             httpGet:
               port: 8080
               path: /actuator/health
          env:
            - name: my_prop
              valueFrom:
                configMapKeyRef:
                  key: my_prop
                  name: k8s-test-config-map
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi

      restartPolicy: Always
  selector:
    matchLabels:
      app: k8s-test-deployment

